Core Concepts week 1 day 2 updated
microsoft/win-student-devs pull request #28
Opened 2022-02-11 19:44 UTC by beth-panx

---

⚠️ Merge/Release date 2/15

---

Updates:
- Week 1 day 2 article

***Please ignore day 1 changes. They are included in this PR #27**

2022-02-12 00:13 UTC, aarongustafson requested changes
Minor edits

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> +Note that Microsoft Edge will let you use `http://localhost` (non-HTTPS) to preview and test your PWA locally - _for debugging purposes only_.
```suggestion
Note that browsers will let you use `http://localhost` (non-HTTPS) to preview and test your PWA locally - _for debugging purposes only_.
```

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> + * **Cache API**. Service Workers can access client-side cache and asynchronous storage options (like IndexedDB, Local & Session Storage) to proactively store resources for offline access or performa
```suggestion
 * **Cache API**. Service Workers can access client-side Cache as well as asynchronous storage options (like IndexedDB) to proactively store resources for offline access or performance efficiency.
```

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> + * **Cache API**. Service Workers can access client-side cache and asynchronous storage options (like IndexedDB, Local & Session Storage) to proactively store resources for offline access or performa
`localStorage` & `sessionStorage` are synchronous APIs and unavailable to Service Workers.

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> +We see it meets basic requirements (_has a service worker_) and implements some recommended and optional behaviors (_works offline_, _uses periodic sync_, _uses background sync_) for a better PWA exp
```suggestion
We see it meets the basic requirements (_has a service worker_) and implements some recommended and optional behaviors (_works offline_, _uses periodic sync_, _uses background sync_) for a better PWA experience.
```

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> +So we've made the PWA secure and ensure reliable, network-independent operation. But how do we make it _installable_ like a native app?
```suggestion
So we've made the PWA secure and ensured reliable, network-independent operation. But how do we make it _installable_ like a native app? 
```

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> +That's where the [Web Application Manifest](https://aka.ms/learn-PWA/30Days-1.2/docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/web-app-manifests) comes in. It's a [W3C S
```suggestion
That's where the [Web Application Manifest](https://aka.ms/learn-PWA/30Days-1.2/docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/web-app-manifests) comes in. It's a [W3C Specification](https://aka.ms/learn-PWA/30Days-1.2/www.w3.org/TR/appmanifest) defining **a JSON-based file format** that provides developers with a **centralized place to put metadata** associated with apps.
```

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> + * Create your _manifest.json_ file and associate it with your PWA by referencing it in the `<head>` section of your HTML page (see below).
```suggestion
 * Create your _manifest.json_ file and associate it with your PWA by referencing it in the `head` of your HTML page (see below). 
```

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> + * Scan the `Applications` tab - do you see the `manifest.json` file?
They could also see when it’s loaded in the Network tab :-)

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> +Look at your PWABuilder report from Task 2. Here's what that looks like for DevTools Tips.
```suggestion
Look at your PWABuilder report from Task 2. Here's what that looks like for DevTools Tips:
```

2022-02-12 00:13 UTC, aarongustafson commented on docs/30DaysOfPWA/core-concepts/02.md
> + - PWAs use open web technologies to implement progressive-enhancement techniqiues in a cross-brower compatible way.
```suggestion
 - PWAs use open web technologies to implement progressive-enhancement techniques in a cross-brower compatible way.
```

2022-02-14 18:42 UTC, beth-panx commented on docs/30DaysOfPWA/core-concepts/02.md
> + * Scan the `Applications` tab - do you see the `manifest.json` file?
```suggestion
 * Scan the `Applications` or `Network` tab - do you see the `manifest.json` file?
```

2022-02-14 18:45 UTC, beth-panx commented
@aarongustafson - I updated the article based on your suggestions. Only one about HTTPS on GitHub page that I didn't change.

2022-02-14 18:55 UTC, zateutsch approved these changes

2022-02-15 00:46 UTC, merged