Week 4 Day 5 update: web components
microsoft/win-student-devs pull request #74
Opened 2022-03-04 20:33 UTC by zateutsch

2022-03-05 00:33 UTC, nmetulev reviewed
Awesome work

2022-03-05 00:33 UTC, nmetulev commented on docs/30DaysOfPWA/platforms-practices/05.md
> +FAST isn't the only tool for building web components. For example, the PWA starter uses [lit](https://lit.dev/docs/), which is another web components framework.
You could link here to all the ways you can create a web component - developers can find the framework that is right for them https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/

2022-03-07 09:18 UTC, captainbrosset reviewed
I like this! Great work. I left a few minor comments.
Just one thing, I think we miss a bit of a stronger point about why web components make sense for PWAs. The article says that the maintainability aspect isn't only true for PWAs, but for all apps. And the article doesn't provide other arguments.
We might want to elaborate on the advantages of using standard tech, and having a faster load time (smaller framework, or no framework at all). What do you think?

2022-03-07 09:18 UTC, captainbrosset commented on docs/30DaysOfPWA/platforms-practices/05.md
> +Web Components are a **Web Standard**, which means they are considered a fundamental model for component behavior on the Web. This means we can rely on the web components we use and build to work jus
A bit confused by this sentence: "This means we can rely on the web components we use and build to work just about everywhere". Is there a verb missing somewhere?

2022-03-07 09:18 UTC, captainbrosset commented on docs/30DaysOfPWA/platforms-practices/05.md
> +There are lots of framework options for building web components, but today we'll be using [the FAST framework](https://www.fast.design/docs/introduction) to see a beginner example.
Is it worth mentioning here that you can also use "vanilla" web components too? Like, you don't need a framework to get started. And depending on the complexity of your organization and project, it might not make sense to use one at all.

2022-03-07 09:18 UTC, captainbrosset commented on docs/30DaysOfPWA/platforms-practices/05.md
> +![](_media/movie-review.png)
Missing alt text here.

2022-03-07 16:46 UTC, EisenbergEffect requested changes
I caught a bug in the code sample that should definitely be addressed before publishing. I added a few other thoughts as well.

2022-03-07 16:46 UTC, EisenbergEffect commented on docs/30DaysOfPWA/platforms-practices/05.md
> +    @attr name: string = "No Movie Listed";
Might want to avoid using `name` since that has other uses in HTML.

2022-03-07 16:46 UTC, EisenbergEffect commented on docs/30DaysOfPWA/platforms-practices/05.md
> +<movie-review movieName="Fast and Furious: Tokyo Drift" rating="5">
There's a bug in the code sample here. `movieName` isn't an attribute on the custom element as defined. Also, HTML attributes are case normalized by the browser so you'd want this to be `moviename` to avoid confusion.

2022-03-07 16:46 UTC, EisenbergEffect commented on docs/30DaysOfPWA/platforms-practices/05.md
> +There are lots of framework options for building web components, but today we'll be using [the FAST framework](https://www.fast.design/docs/introduction) to see a beginner example.
If we do add that, I think a good idea would be to point out that FAST and Lit aren't like typical JavaScript frameworks in that they are very small and fully interoperate through standards. So, the concerns of "choosing a framework" or event "vanilla js" are not quite the same as people may be used to.

2022-03-07 16:46 UTC, EisenbergEffect commented on docs/30DaysOfPWA/platforms-practices/05.md
> +If you want more depth on building quality components and adding functionality, check out the [FAST documentation](https://www.fast.design/docs/introduction).
```suggestion
If you want more depth on building quality components and adding functionality, or if you want to leverage the dozens of pre-built components FAST offers, check out the [FAST documentation](https://www.fast.design/docs/introduction).
```

I thought it might be nice to squeeze a bit in there about the other things FAST offers besides just the library for building components.

2022-03-07 16:46 UTC, EisenbergEffect commented on docs/30DaysOfPWA/platforms-practices/05.md
> +There's a ton of options, but for the sake of simplicity, we'll just be looking at one technology we can leverage in maintainable projects: **web components!**
If any additional content is desired for this section on "why web components", the FAST site has some points you can feel free to borrow: https://www.fast.design/docs/resources/why-web-components

2022-03-08 23:08 UTC, zateutsch commented on docs/30DaysOfPWA/platforms-practices/05.md
> +![](_media/movie-review.png)
```suggestion
![Image of our movie review web component](_media/movie-review.png)
```

2022-03-08 23:34 UTC, zateutsch commented
> I like this! Great work. I left a few minor comments. Just one thing, I think we miss a bit of a stronger point about why web components make sense for PWAs. The article says that the maintainability aspect isn't only true for PWAs, but for all apps. And the article doesn't provide other arguments. We might want to elaborate on the advantages of using standard tech, and having a faster load time (smaller framework, or no framework at all). What do you think?

I added a bit more in the Web Standards section about what Web Components bring to the table. I also included the link that Rob provided to give more depth on why web components.

2022-03-10 22:22 UTC, beth-panx commented on docs/30DaysOfPWA/platforms-practices/05.md
> +Welcome to Week 4, Day 5 of the [30 Days of PWA](https://aka.ms/learn-pwa/30Days-blog) series! Now that we've seen how to start building PWAs and what basic and advanced capabilites they bring, it's
```suggestion
Welcome to Week 4, Day 5 of the [30 Days of PWA](https://aka.ms/learn-pwa/30Days-blog) series! Now that we've seen how to start building PWAs and what basic and advanced capabilities they bring, it's time to dive into what a _good_ PWA really looks like it, and how we can start to build quality applications ourselves. Week 4 is all about some of the best practices and technologies you can use to really polish up your PWA.
```

2022-03-10 22:22 UTC, beth-panx commented on docs/30DaysOfPWA/platforms-practices/05.md
>  ![Placeholder Banner Only. Replace when final assets ready.](_media/day5.png)
```suggestion
![image of title and author.](_media/day5.png)
```

2022-03-10 22:23 UTC, beth-panx commented on docs/30DaysOfPWA/platforms-practices/05.md
> +When we create a web component, all of our behavior, html, and styling is contained to that component. We don't have to worry about it interfering with other aspects of our project when we include ou
```suggestion
When we create a web component, all of our behavior, html, and styling is contained to that component. We don't have to worry about it interfering with other aspects of our project when we include our component in our application. This a huge bonus for maintainability: it allows us to segment our code and avoid overly-verbose spaghetti code in our project files. Additionally, for larger PWAs that may have multiple developers working at once, web components allow for concurrent contribution by keeping unrelated components separated from each other.
```

2022-03-10 22:24 UTC, beth-panx commented on docs/30DaysOfPWA/platforms-practices/05.md
> +
```suggestion
Web Components are a **Web Standard**, which means they are considered a fundamental model for component behavior on the Web. This means we can rely on the web components we build to work just about everywhere:

![Compatibility list for web components](_media/component-web-standards.png)

Another benefit to this is that web component frameworks are generally small and fully interoperable. This means that you can use web components within larger modern frameworks (like React or Angular) and they will still work as expected. You can even ditch the frameworks all together and build web components in vanilla javascript.

As far as maintainability goes for our PWAs, this is great. We know our components will work in different browsers and frameworks, and we don't have to write extra code to keep our project functional. When we go to update or extend one of our components, we can work freely without worrying about compatibility issues. Web Standards also generally guarantee forward-compatibility: our components will still work as the open web grows and changes.

```

2022-03-10 22:25 UTC, beth-panx commented on docs/30DaysOfPWA/platforms-practices/05.md
> +![Compatability list for web components](_media/component-web-standards.png)
```suggestion
![Compatibility list for web components](_media/component-web-standards.png)
```

2022-03-10 22:25 UTC, beth-panx commented on docs/30DaysOfPWA/platforms-practices/05.md
> +Another benefit to this is that web component frameworks are generally small and fuly interoperable. This means that you can use web components within larger modern frameworks (like React or Angular)
```suggestion
Another benefit to this is that web component frameworks are generally small and fully interoperable. This means that you can use web components within larger modern frameworks (like React or Angular) and they will still work as expected. You can even ditch the frameworks all together and build web components in vanilla javascript.
```

2022-03-10 22:25 UTC, beth-panx commented on docs/30DaysOfPWA/platforms-practices/05.md
> +As far as maintainability goes for our PWAs, this is great. We know our components will work in different browsers and frameworks, and we don't have to write extra code to keep our project functional
```suggestion
As far as maintainability goes for our PWAs, this is great. We know our components will work in different browsers and frameworks, and we don't have to write extra code to keep our project functional. When we go to update or extend one of our components, we can work freely without worrying about compatibility issues. Web Standards also generally guarantee forward-compatibility: our components will still work as the open web grows and changes.
```

2022-03-10 22:26 UTC, beth-panx commented on docs/30DaysOfPWA/platforms-practices/05.md
> +We now have a reuseable `<movie-review>` component. As you can see, this example is fairly naive, but you can start to imagine the possibilites. Let's say we had a more in-depth `<movie-review>` comp
```suggestion
We now have a reusable `<movie-review>` component. As you can see, this example is fairly naive, but you can start to imagine the possibilities. Let's say we had a more in-depth `<movie-review>` component that we could use inside a related `<movie-review-list>` component. We could then change the appearance and functionality of our movie reviews separate from the list that displays them, allowing us extend and update our `<movie-review>` component regardless of the environment it lives in. Encapsulated and maintainable!
```

2022-03-10 22:27 UTC, beth-panx approved these changes
I made edits on typos.

2022-03-11 00:12 UTC, merged